
name: CI - Deploy

on:
  push:
    branches:
      - gitcopy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run deploy
