
name: CI - Deploy

on:
  push:
    branches:
      - gitcopy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        git config --global user.email "spreadyourlinks@iamdhrumilshah.com"
        git config --global user.name "SpreadYourLinksAuto"
        npm install
        npm run deploy
