
name: CI - Front-end

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - run: 'npm run export'
        
    - name: Pushes to github pages repo
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'export'
        destination-github-username: 'spreadyourlinks'
        destination-repository-name: 'spreadyourlinks.github.io'
        user-email: me@iamdhrumilshah.com
        target-branch: gitcopy

    - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - run: |
        git config --global user.email "spreadyourlinks@iamdhrumilshah.com"
        git config --global user.name "SpreadYourLinksAuto"
        npm install
        npm run deploy
